### ISSUE TITLE
Readme topics to add for first milestone

### ISSUE THREAD

**Issue by metalhead777** [metalhead777/blinCAN#1]
- [ ] Short function description
    - [ ] Add picture of physical PCB
    - [x] Include Desert Eyes link
    - [ ] Add [EEVBlog-style OSHW-logo](https://www.eevblog.com/oshw/)
    - [x] Current development state

- [ ] Commissioning description
    - [ ] Power requirements (current: calculated, with LED output off and LED output 100% on)
    - [ ] Connection diagram: programming, communications, power input
    - [ ] LED connector pinout graphics

- [ ] Programming instructions (no firmware yet, maybe use Arduino bootloader as sample)
    - [ ] Windows
    - [ ] Linux
    - [ ] MacOS
    - [ ] Include list of programming adaptors successfully tested
    - [ ] Include Reset-button issue!

- [ ] Device communication reference
    - [ ] Internal (SPI, refer to TLC5947 datasheet)
    - [ ] External (CAN, not documented yet!)
    - [ ] Addressing scheme (3 Bit = 8 addresses in this version, can be further improved)

- [x] List of current bugs and issues

- [x] List of planned future changes/improvements

- [x] List of references to open source hardware/software used in this project
    - [x] KiCAD
    - [x] Arduino nano Rev. 3
    - [x] Arduino SparkFun CAN-Bus Shield Rev. 13

- [x] List of active contributors to this project
    - [x] Firmware programmers
    - [x] Library programmers

- [x] Add a license
    - [x] Add note about no warranty given
