### ISSUE TITLE
Work on Hardware to do for first milestone

### ISSUE THREAD

**Issue by metalhead777** [metalhead777/blinCAN#2]
- [x] Delete version history from previous project development
- [x] Sanitize any personal data in schematic and layout
- [x] Remove copyrighted logo from previous project development from schematic and layout
- [x] Change text to silkscreen layer on layout
- [x] Add [EEVBlog-style OSHW-logo](https://www.eevblog.com/oshw/)
- [x] Remove TLC5947 breakout board footprint from layout
- [x] ~~Change order of address indication LEDs and addressing switch to MSB first~~
- [x] Remove notes and unnecessary measurements from schematic and layout
- [x] Set name to project name, without version
- [x] Set date to initial project setup
- [x] Set Revision number to 0.1 as initial project setup
- [x] Set KiCAD to newest version
- [x] Clean symbols and footprints, use only standard libraries if possible
- [x] Put special symbols and footprints into one project-specific library
- [x] Produce coherent component annotation
- [x] Rename components to only value, remove ordering numbers/names (refer to BOM for further corrections)
- [x] ~~Generate new BOM file without distributor information~~
- [x] Remove datasheets and mechanics folders
- [x] Add fiducial marks
- [x] Produce Gerber files only at the very end of the first milestone
